# Generated by cucumber-sinatra. (2012-09-19 22:41:50 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Lab2

class Lab2World
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Lab2World.new
end
